# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: The Whole Tale
email: wholetale-exec@googlegroups.com
description: >- # this means to ignore newlines until "baseurl:"
    Whole Tale will enable researchers to examine, transform and then seamlessly
    republish research data that was used in an article. As a result, these "living
    articles" enable new discovery by allowing researchers to construct
    representations and syntheses of data.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://wholetale.org/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: wholetale
github_username:  whole-tale

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
